import PDFDocument from "pdfkit";
import { PAGE, M, CW, C, F, S, complexityColors } from "./constants";
import { fc, fillRect, fillRoundRect, hline } from "./pageManager";
import { ProfessionalServicesReport } from "../../reports/professionalServicesReport";

export function renderCover(
  doc: InstanceType<typeof PDFDocument>,
  report: ProfessionalServicesReport,
  logoBuffer: Buffer | null
) {
  // ── Dark header band ──
  fillRect(doc, 0, 0, PAGE.W, 210, C.primaryDark);

  // Decorative circle (top right)
  fc(doc, C.primary);
  doc.circle(PAGE.W - 20, 50, 80).fillOpacity(0.25).fill();
  doc.fillOpacity(1);

  // Logo
  if (logoBuffer) {
    doc.image(logoBuffer, M, 24, { width: 110 });
  } else {
    fc(doc, "#FFFFFF");
    doc.font(F.bold).fontSize(16).text("KlayyTech", M, 30);
  }

  // Subtitle label
  fc(doc, "rgba(255,255,255,0.6)");
  doc.font(F.regular).fontSize(10)
    .text("PROFESSIONAL SERVICES ASSESSMENT REPORT", M, 90, { characterSpacing: 1 });

  // Company name
  fc(doc, "#FFFFFF");
  doc.font(F.bold).fontSize(28)
    .text(report.companyProfile.companyName, M, 110, { width: CW - 40 });

  // Scenario name
  fc(doc, C.primaryBorder);
  doc.font(F.regular).fontSize(13)
    .text(report.scenarioResult.scenarioName, M, 158, { width: CW });

  // ── Complexity badge ──
  const cc = complexityColors(report.complexity.level);
  fillRoundRect(doc, M, 192, 180, 28, 4, cc.bg);
  fc(doc, cc.text);
  doc.font(F.bold).fontSize(11)
    .text(report.complexity.level.toUpperCase(), M + 10, 200, { width: 160 });

  // ── Key metrics row ──
  const metricY = 248;
  const metrics = [
    { label: "ESTIMATED EFFORT",     value: report.effort.label },
    { label: "INDICATIVE COST",      value: report.pricing.label },
    { label: "ASSESSMENT CONFIDENCE",value: `${report.confidence.score}%` },
  ];

  metrics.forEach((m, i) => {
    const x = M + i * (CW / 3);
    const colW = CW / 3 - 8;

    fillRoundRect(doc, x, metricY, colW, 52, 4, C.bg);
    fc(doc, C.textLight);
    doc.font(F.regular).fontSize(7)
      .text(m.label, x + 10, metricY + 10, { width: colW - 20, characterSpacing: 0.5 });
    fc(doc, C.text);
    doc.font(F.bold).fontSize(14)
      .text(m.value, x + 10, metricY + 23, { width: colW - 20 });
  });

  // ── Company overview grid ──
  const gridY = 332;
  hline(doc, M, gridY, CW, C.border);
  const gridItems = [
    { label: "INDUSTRY",  value: report.companyProfile.industry ?? "—" },
    { label: "SIZE",      value: report.companyProfile.employeesAndUsers ?? "—" },
    { label: "IT TEAM",   value: report.companyProfile.itTeam ?? "—" },
    { label: "REPORT ID", value: report.meta.reportId },
    { label: "GENERATED", value: new Date(report.meta.generatedAt).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }) },
    { label: "VERSION",   value: `Scenario v${report.meta.scenarioVersion}` },
  ];

  const colW2 = CW / 3;
  gridItems.forEach((item, i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const x = M + col * colW2;
    const y = gridY + 14 + row * 44;

    fc(doc, C.textLight);
    doc.font(F.regular).fontSize(7)
      .text(item.label, x, y, { characterSpacing: 0.5 });
    fc(doc, C.text);
    doc.font(F.bold).fontSize(11)
      .text(item.value, x, y + 12, { width: colW2 - 10 });
  });

  hline(doc, M, gridY + 106, CW, C.border);

  // ── Prepared by ──
  const prepY = gridY + 120;
  fc(doc, C.textMuted);
  doc.font(F.regular).fontSize(9)
    .text("PREPARED BY", M, prepY, { characterSpacing: 0.5 });
  fc(doc, C.text);
  doc.font(F.bold).fontSize(11)
    .text("KlayyTech Cloud Solutions Team", M, prepY + 14);
  fc(doc, C.textMuted);
  doc.font(F.regular).fontSize(9)
    .text("support@klayytech.com", M, prepY + 28);

  // ── CONFIDENTIAL stamp ──
  fc(doc, C.border);
  doc.rect(M, PAGE.H - 52, 130, 20).stroke();
  fc(doc, C.textLight);
  doc.font(F.bold).fontSize(8)
    .text("CONFIDENTIAL", M + 8, PAGE.H - 47, { characterSpacing: 1 });

  // ── Footer ──
  fc(doc, C.textLight);
  doc.font(F.regular).fontSize(7.5)
    .text(
      "Generated by KlayyTech CloudReady  ·  Professional Services Assessment Platform",
      M, PAGE.H - 24, { width: CW, align: "center" }
    );
}